services:
  database:
    container_name: postgres
    image: postgres:13
    shm_size: 1g
    environment:
      POSTGRES_USER: "freefeed"
      POSTGRES_PASSWORD: "freefeed"
      POSTGRES_INITDB_ARGS: "--locale=en_US.UTF-8 --encoding=utf-8"
    command: >-
      -c max_connections=20 
      -c shared_buffers=1GB 
      -c effective_cache_size=3GB 
      -c maintenance_work_mem=256MB 
      -c checkpoint_completion_target=0.9 
      -c wal_buffers=16MB 
      -c default_statistics_target=100 
      -c random_page_cost=1.1 
      -c effective_io_concurrency=200 
      -c work_mem=26214kB 
      -c min_wal_size=1GB 
      -c max_wal_size=4GB 
      -c max_worker_processes=2 
      -c max_parallel_workers_per_gather=1 
      -c max_parallel_workers=2 
      -c max_parallel_maintenance_workers=1 
      -c fsync=off
      -c full_page_writes=off
      -c synchronous_commit=off
    ports:
      - '15432:5432'
    volumes:
      - './pgdata/:/var/lib/postgresql/data/'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './tsearch_data/:/usr/share/postgresql/13/tsearch_data/'

  redis:
    container_name: 'redis'
    image: 'redis:6'
    ports:
      - '16379:6379'
    volumes:
      - './redisdata/:/data/'

# volumes:
#   './pgdata/':
#   './redisdata/':
#   './init.sql':
      